spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
  datasource:
    url: jdbc:mysql://192.168.2.101:3306/blog
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

