name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: client

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      # Runs a single command using the runners shell
      - name: Tencent CloudBase update
        env:
          ENV_ID: ${{secrets.SECRET_ID}}
          SECRET_ID: ${{secrets.SECRET_ID}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
        run: |
          sudo pnpm install -g @cloudbase/cli --loglevel=error 
          tcb login --apiKeyId "$SECRET_ID" --apiKey "$SECRET_KEY"
          tcb framework deploy -e "$ENV_ID"